# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generates <Top>SimMem.sv: the Chisel-emitted core with its AXI master
port connected to axi_sim_mem instead of exposed to the testbench.

Every other port is passed through with the same name, so the cocotb
CoreMiniAxiInterface drives the wrapper exactly as it drives the bare core
(it detects the missing io_axi_master_* ports and switches to the DDR
backdoor for external memory).

Usage: gen_axi_sim_mem_wrapper.py <core.sv> <Top> <out.sv> [--prefix io_axi_master]
"""

import argparse
import re


def parse_ports(sv_text, top):
    m = re.search(r"^module\s+" + re.escape(top) + r"\s*\((.*?)^\);", sv_text,
                  re.S | re.M)
    if not m:
        raise SystemExit(f"module {top} not found")
    ports = []
    direction = width = None
    for raw in m.group(1).split(","):
        tok = raw.strip()
        if not tok:
            continue
        pm = re.match(r"(?:(input|output|inout)\s+)?(?:(\[[^\]]+\])\s+)?(\w+)$", tok)
        if not pm:
            raise SystemExit(f"cannot parse port: {tok!r}")
        d, w, name = pm.groups()
        if d:  # a new direction resets the width unless one is given
            direction, width = d, w
        elif w:
            width = w
        ports.append((direction, width, name))
    return ports


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("core_sv")
    ap.add_argument("top")
    ap.add_argument("out_sv")
    ap.add_argument("--prefix", default="io_axi_master")
    ap.add_argument("--clk", default="io_aclk")
    ap.add_argument("--rst_n", default="io_aresetn")
    args = ap.parse_args()

    ports = parse_ports(open(args.core_sv).read(), args.top)
    p = args.prefix
    ext = [(d, w, n) for d, w, n in ports if not n.startswith(p + "_")]
    mem = {n: (d, w) for d, w, n in ports if n.startswith(p + "_")}

    def width_of(name):
        w = mem[name][1]
        return int(w.strip("[]").split(":")[0]) + 1 if w else 1

    addr_w = width_of(f"{p}_read_addr_bits_addr")
    data_w = width_of(f"{p}_read_data_bits_data")
    id_w = width_of(f"{p}_read_addr_bits_id")

    lines = [
        "// GENERATED by hdl/verilog/gen_axi_sim_mem_wrapper.py. Do not edit.",
        f"module {args.top}SimMem(",
    ]
    lines.append(",\n".join(
        f"  {d} {w + ' ' if w else ''}{n}" for d, w, n in ext))
    lines.append(");")
    # Internal nets get a prefix that does not match the testbench's public
    # "io_*" glob (rules/default.vlt.tpl); otherwise cocotb still sees
    # io_axi_master_* and drives them alongside the memory model.
    def net(n):
        return "ddr_" + n[len(p) + 1:] if n in mem else n
    for n, (d, w) in mem.items():
        lines.append(f"  logic {w + ' ' if w else ''}{net(n)};")
    lines.append(f"  {args.top} core (")
    lines.append(",\n".join(f"    .{n}({net(n)})" for _, _, n in ports))
    lines.append("  );")
    ch = {  # axi_sim_mem port -> core port
        "aw_valid": "write_addr_valid", "aw_ready": "write_addr_ready",
        "aw_addr": "write_addr_bits_addr", "aw_id": "write_addr_bits_id",
        "aw_len": "write_addr_bits_len", "aw_size": "write_addr_bits_size",
        "aw_burst": "write_addr_bits_burst",
        "w_valid": "write_data_valid", "w_ready": "write_data_ready",
        "w_data": "write_data_bits_data", "w_strb": "write_data_bits_strb",
        "w_last": "write_data_bits_last",
        "b_valid": "write_resp_valid", "b_ready": "write_resp_ready",
        "b_id": "write_resp_bits_id", "b_resp": "write_resp_bits_resp",
        "ar_valid": "read_addr_valid", "ar_ready": "read_addr_ready",
        "ar_addr": "read_addr_bits_addr", "ar_id": "read_addr_bits_id",
        "ar_len": "read_addr_bits_len", "ar_size": "read_addr_bits_size",
        "ar_burst": "read_addr_bits_burst",
        "r_valid": "read_data_valid", "r_ready": "read_data_ready",
        "r_data": "read_data_bits_data", "r_id": "read_data_bits_id",
        "r_resp": "read_data_bits_resp", "r_last": "read_data_bits_last",
    }
    lines.append(f"  axi_sim_mem #(.ADDR_W({addr_w}), .DATA_W({data_w}), .ID_W({id_w})) ddr (")
    conns = [f"    .clk({args.clk})", f"    .rst_n({args.rst_n})"]
    conns += [f"    .{a}(ddr_{b})" for a, b in ch.items()]
    lines.append(",\n".join(conns))
    lines.append("  );")
    lines.append("endmodule")
    open(args.out_sv, "w").write("\n".join(lines) + "\n")
    print(f"{args.out_sv}: {len(ext)} passthrough ports, {len(mem)} memory ports, "
          f"ADDR_W={addr_w} DATA_W={data_w} ID_W={id_w}")


if __name__ == "__main__":
    main()
